POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "Jod32",
  "surname": "3dfe2",
  "email": "sod5sa@gmail"
}

###
GET http://localhost:8080/members

###
GET http://localhost:8080/members/sod5sa@gmail